// Code generated by protoc-gen-go. DO NOT EDIT.
// source: helloworld.proto

package helloworld

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message containing the user's name.
type HelloRequest struct {
	Times                int32    `protobuf:"varint,1,opt,name=times,proto3" json:"times,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloRequest) Reset()         { *m = HelloRequest{} }
func (m *HelloRequest) String() string { return proto.CompactTextString(m) }
func (*HelloRequest) ProtoMessage()    {}
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{0}
}

func (m *HelloRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloRequest.Unmarshal(m, b)
}
func (m *HelloRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloRequest.Marshal(b, m, deterministic)
}
func (m *HelloRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloRequest.Merge(m, src)
}
func (m *HelloRequest) XXX_Size() int {
	return xxx_messageInfo_HelloRequest.Size(m)
}
func (m *HelloRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HelloRequest proto.InternalMessageInfo

func (m *HelloRequest) GetTimes() int32 {
	if m != nil {
		return m.Times
	}
	return 0
}

type HelloDetail struct {
	Hoge                 string   `protobuf:"bytes,1,opt,name=hoge,proto3" json:"hoge,omitempty"`
	Fuga                 string   `protobuf:"bytes,2,opt,name=fuga,proto3" json:"fuga,omitempty"`
	Piyo                 string   `protobuf:"bytes,3,opt,name=piyo,proto3" json:"piyo,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HelloDetail) Reset()         { *m = HelloDetail{} }
func (m *HelloDetail) String() string { return proto.CompactTextString(m) }
func (*HelloDetail) ProtoMessage()    {}
func (*HelloDetail) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{1}
}

func (m *HelloDetail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloDetail.Unmarshal(m, b)
}
func (m *HelloDetail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloDetail.Marshal(b, m, deterministic)
}
func (m *HelloDetail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloDetail.Merge(m, src)
}
func (m *HelloDetail) XXX_Size() int {
	return xxx_messageInfo_HelloDetail.Size(m)
}
func (m *HelloDetail) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloDetail.DiscardUnknown(m)
}

var xxx_messageInfo_HelloDetail proto.InternalMessageInfo

func (m *HelloDetail) GetHoge() string {
	if m != nil {
		return m.Hoge
	}
	return ""
}

func (m *HelloDetail) GetFuga() string {
	if m != nil {
		return m.Fuga
	}
	return ""
}

func (m *HelloDetail) GetPiyo() string {
	if m != nil {
		return m.Piyo
	}
	return ""
}

// The response message containing the greetings
type HelloReply struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	From                 string         `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	Body                 string         `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	Details              []*HelloDetail `protobuf:"bytes,4,rep,name=details,proto3" json:"details,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *HelloReply) Reset()         { *m = HelloReply{} }
func (m *HelloReply) String() string { return proto.CompactTextString(m) }
func (*HelloReply) ProtoMessage()    {}
func (*HelloReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_17b8c58d586b62f2, []int{2}
}

func (m *HelloReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HelloReply.Unmarshal(m, b)
}
func (m *HelloReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HelloReply.Marshal(b, m, deterministic)
}
func (m *HelloReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HelloReply.Merge(m, src)
}
func (m *HelloReply) XXX_Size() int {
	return xxx_messageInfo_HelloReply.Size(m)
}
func (m *HelloReply) XXX_DiscardUnknown() {
	xxx_messageInfo_HelloReply.DiscardUnknown(m)
}

var xxx_messageInfo_HelloReply proto.InternalMessageInfo

func (m *HelloReply) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HelloReply) GetFrom() string {
	if m != nil {
		return m.From
	}
	return ""
}

func (m *HelloReply) GetBody() string {
	if m != nil {
		return m.Body
	}
	return ""
}

func (m *HelloReply) GetDetails() []*HelloDetail {
	if m != nil {
		return m.Details
	}
	return nil
}

func init() {
	proto.RegisterType((*HelloRequest)(nil), "helloworld.HelloRequest")
	proto.RegisterType((*HelloDetail)(nil), "helloworld.HelloDetail")
	proto.RegisterType((*HelloReply)(nil), "helloworld.HelloReply")
}

func init() { proto.RegisterFile("helloworld.proto", fileDescriptor_17b8c58d586b62f2) }

var fileDescriptor_17b8c58d586b62f2 = []byte{
	// 262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0x3b, 0x31,
	0x10, 0xc5, 0xff, 0xbb, 0x6d, 0xff, 0xd5, 0xa9, 0xa8, 0x04, 0xd1, 0xa0, 0x97, 0xb2, 0x78, 0xe8,
	0x69, 0xa9, 0xf5, 0x0b, 0x48, 0x11, 0x54, 0xbc, 0x94, 0xf5, 0xe0, 0x79, 0x6b, 0xc6, 0x6d, 0x20,
	0xcb, 0xc4, 0x6c, 0x4a, 0xcd, 0xb7, 0x97, 0xc9, 0x6e, 0x75, 0x41, 0x6f, 0x6f, 0x5e, 0x7e, 0x79,
	0x99, 0x3c, 0x38, 0xdd, 0xa0, 0x31, 0xb4, 0x23, 0x67, 0x54, 0x6e, 0x1d, 0x79, 0x12, 0xf0, 0xe3,
	0x64, 0xd7, 0x70, 0xf4, 0xc8, 0x53, 0x81, 0x1f, 0x5b, 0x6c, 0xbc, 0x38, 0x83, 0x91, 0xd7, 0x35,
	0x36, 0x32, 0x99, 0x26, 0xb3, 0x51, 0xd1, 0x0e, 0xd9, 0x13, 0x4c, 0x22, 0x75, 0x8f, 0xbe, 0xd4,
	0x46, 0x08, 0x18, 0x6e, 0xa8, 0xc2, 0xc8, 0x1c, 0x16, 0x51, 0xb3, 0xf7, 0xbe, 0xad, 0x4a, 0x99,
	0xb6, 0x1e, 0x6b, 0xf6, 0xac, 0x0e, 0x24, 0x07, 0xad, 0xc7, 0x3a, 0xdb, 0x01, 0x74, 0x0f, 0x5a,
	0x13, 0xc4, 0x31, 0xa4, 0x5a, 0x75, 0x39, 0xa9, 0x56, 0x31, 0xc5, 0x51, 0xfd, 0x9d, 0xe2, 0xa8,
	0x66, 0x6f, 0x4d, 0x2a, 0xec, 0x53, 0x58, 0x8b, 0x1b, 0x18, 0xab, 0xb8, 0x4b, 0x23, 0x87, 0xd3,
	0xc1, 0x6c, 0xb2, 0xb8, 0xc8, 0x7b, 0xdf, 0xec, 0xed, 0x5a, 0xec, 0xb9, 0xc5, 0x33, 0x8c, 0x1f,
	0x1c, 0xa2, 0x47, 0x27, 0xee, 0xe0, 0xe0, 0xa5, 0x0c, 0x91, 0x12, 0xf2, 0xd7, 0xc5, 0xae, 0x8a,
	0xcb, 0xf3, 0x3f, 0x4e, 0xac, 0x09, 0xd9, 0xbf, 0x79, 0xb2, 0x9c, 0xc3, 0x95, 0xa6, 0xbc, 0x72,
	0xf6, 0x2d, 0xc7, 0xcf, 0xb2, 0xb6, 0x06, 0x9b, 0x1e, 0xbd, 0x3c, 0x89, 0xf8, 0x2b, 0xeb, 0x15,
	0x57, 0xbe, 0x4a, 0xd6, 0xff, 0x63, 0xf7, 0xb7, 0x5f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x70, 0xec,
	0x5a, 0x20, 0x8f, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// GreeterClient is the client API for Greeter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type GreeterClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloClient, error)
}

type greeterClient struct {
	cc *grpc.ClientConn
}

func NewGreeterClient(cc *grpc.ClientConn) GreeterClient {
	return &greeterClient{cc}
}

func (c *greeterClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (Greeter_SayHelloClient, error) {
	stream, err := c.cc.NewStream(ctx, &_Greeter_serviceDesc.Streams[0], "/helloworld.Greeter/SayHello", opts...)
	if err != nil {
		return nil, err
	}
	x := &greeterSayHelloClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Greeter_SayHelloClient interface {
	Recv() (*HelloReply, error)
	grpc.ClientStream
}

type greeterSayHelloClient struct {
	grpc.ClientStream
}

func (x *greeterSayHelloClient) Recv() (*HelloReply, error) {
	m := new(HelloReply)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// GreeterServer is the server API for Greeter service.
type GreeterServer interface {
	// Sends a greeting
	SayHello(*HelloRequest, Greeter_SayHelloServer) error
}

// UnimplementedGreeterServer can be embedded to have forward compatible implementations.
type UnimplementedGreeterServer struct {
}

func (*UnimplementedGreeterServer) SayHello(req *HelloRequest, srv Greeter_SayHelloServer) error {
	return status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}

func RegisterGreeterServer(s *grpc.Server, srv GreeterServer) {
	s.RegisterService(&_Greeter_serviceDesc, srv)
}

func _Greeter_SayHello_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HelloRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(GreeterServer).SayHello(m, &greeterSayHelloServer{stream})
}

type Greeter_SayHelloServer interface {
	Send(*HelloReply) error
	grpc.ServerStream
}

type greeterSayHelloServer struct {
	grpc.ServerStream
}

func (x *greeterSayHelloServer) Send(m *HelloReply) error {
	return x.ServerStream.SendMsg(m)
}

var _Greeter_serviceDesc = grpc.ServiceDesc{
	ServiceName: "helloworld.Greeter",
	HandlerType: (*GreeterServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "SayHello",
			Handler:       _Greeter_SayHello_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "helloworld.proto",
}
