# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: eafb7a5836361cab76526f6ed4221dcd561c9a56a0de349e4765525e00679670b9e947d0d4e787065052a19176ede29b6c19faee8a1aafcebc3ee7bad0dab60e

test:
  secret_key_base: 70a8bda1b4a9b739eca817a4e38b18ccefc3186a07e38d6305014a44a6b1cf4b426b42fa91f70529c548bead0832893a2b43d6370134256be5b739e0add2902c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
